on:
  release:
    types: [published]

name: Publish binaries to release

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          aarch64-unknown-linux-gnu, i686-unknown-linux-gnu, x86_64-unknown-linux-gnu, # Linux
          aarch64-apple-darwin, x86_64-apple-darwin, # macOS
          aarch64-pc-windows-msvc, x86_64-pc-windows-gnu, x86_64-pc-windows-msvc, # Windows
          x86_64-unknown-freebsd, x86_64-unknown-netbsd # BSD
        ]
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --locked --target ${{ matrix.target }}
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: target/release/${{ matrix.artifact_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.PUBLISH_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
