on:
  release:
    types: [published]

name: Publish binaries to release

jobs:
  publish-most:
    name: Publish for ${{ matrix.conf.target}}
    runs-on: ${{ matrix.conf.os }}
    strategy:
      matrix:
        conf: [
          { os: ubuntu-latest, use-cross: true, target: aarch64-unknown-linux-gnu}, { os: ubuntu-latest, use-cross: true, target: i686-unknown-linux-gnu }, { os: ubuntu-latest, use-cross: false, target: x86_64-unknown-linux-gnu }, # Linux
          # { target: aarch64-apple-darwin }, { target: x86_64-apple-darwin }, # macOS
          { os: windows-latest, use-cross: false, target: i686-pc-windows-gnu }, { os: windows-latest, use-cross: false, target: x86_64-pc-windows-gnu }, # Windows
          { os: ubuntu-latest, use-cross: true, target: x86_64-unknown-freebsd }, { os: ubuntu-latest, use-cross: true, target: x86_64-unknown-netbsd } # BSD
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.conf.target }}
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.conf.use-cross }}
          command: build
          args: --release --locked --target ${{ matrix.conf.target }}
      - name: Where are you writing your shit windows!?
        run: |
          ls
          cd target; ls
          cd ${{ matrix.conf.target }}; ls
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.PUBLISH_TOKEN }}
          file: target/${{ matrix.conf.target }}/release/ci-test
          asset_name: test-${{ matrix.conf.target }}
          tag: ${{ github.ref }}

  publish-macos:
    name: Publish for ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      matrix:
        target: [
          aarch64-apple-darwin, x86_64-apple-darwin, # macOS
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --release --locked --target ${{ matrix.target }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.PUBLISH_TOKEN }}
          file: target/${{ matrix.target }}/release/ci-test
          asset_name: hello-${{ matrix.target }}
          tag: ${{ github.ref }}
